export const headers = [
    "LocalDate", "LocalTime", "UTCOffset",
    "AtvWpt", "Lat", "Long",
    "AltB", "BaroA", "AltMSL",
    "OAT", "IAS", "GndSpd",
    "VSpd", "Pitch", "Roll",
    "LatAc", "NormAc", "HDG",
    "TRK", "volt1", "volt2",
    "amp1", "FQtyL", "FQtyR",
    "E1FFlow", "E1OilT", "E1OilP",
    "E1MAP", "E1RPM", "E1%Pwr",
    "E1CHT1", "E1CHT2", "E1CHT3",
    "E1CHT4", "E1CHT5", "E1CHT6",
    "E1EGT1", "E1EGT2", "E1EGT3",
    "E1EGT4", "E1EGT5", "E1EGT6",
    "E1TIT1", "E1TIT2", "AltGPS",
    "TAS", "HSIS", "CRS",
    "NAV1", "NAV2", "COM1",
    "COM2", "HCDI", "VCDI",
    "WndSpd", "WndDr", "WptDst",
    "WptBrg", "MagVar", "AfcsOn",
    "RollM", "PitchM", "RollC",
    "PitchC", "VSpdG", "GPSfix",
    "HAL", "VAL", "HPLwas",
    "HPLfd", "VPLwas"
];
