//Master list
export const headersAll = [
    { name: "UTC Date", unit: "mm/dd/yy", hide: true, category: "timeinfo"}, 
    { name: "UTC Time", unit: "hh:mm:ss", hide: true, category: "timeinfo"},
    { name: "UTC Offset", unit: "hh:mm", hide: true, category: "timeinfo"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Selected Heading", unit: "Deg", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Selected Altitude", unit: "ft", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "IAS Submode (FLC Vertical Mode)", unit: "kt", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "COM1 ACTV + 100 MHZ", unit: "Mhz", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "COM2 ACTV + 100 MHZ", unit: "Mhz", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "NAV1 ACTV + 100 MHZ", unit: "MHz", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "NAV2 ACTV + 100 MHZ", unit: "MHz",  hide: true, category: "general"}, //
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "OAT (ADC1)", unit: "°C", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""}, 
    { name: "OAT (ADC2)", unit: "°C", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Barometric Correction (Garmin)", unit: "in. Hg", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "PIT Speed", unit: "RPM", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "PIT Torque", unit: "in-lb", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ROL Speed", unit: "RPM", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ROL Torque", unit: "in-lb", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "YAW Speed", unit: "RPM", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "YAW Torque", unit: "in-lb", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ACT WPT Char 1 & 2", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ACT WPT Char 3 & 4", unit: "ASCII", hide: true, category: "general"}, 
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ACT WPT Char 5 & 6 ", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ACT WPT Char 7 & 8", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "CAPS handle pulled", unit: "BIN", hide: true, category: "bool"},
    { name: "CAPS rocket deployed", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Flaps 0%", unit: "BIN", hide: true, category: "bool"},
    { name: "Flaps 50%", unit: "BIN", hide: true, category: "bool"},
    { name: "Flaps 100%", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""}, //
    { name: "IPS NORMAL", unit: "BIN", hide: true, category: "bool"}, 
    { name: "IPS HIGH", unit: "BIN", hide: true, category: "bool"},
    { name: "IPS MAX", unit: "BIN", hide: true, category: "bool"},
    { name: "IPS BACKUP MODE", unit: "BIN", hide: true, category: "bool"},
    { name: "IPS TKS Tank LEFT", unit: "BIN", hide: true, category: "bool"},
    { name: "IPS TKS Tank RIGHT", unit: "BIN", hide: true, category: "bool"},
    { name: "IPS TKS Tank AUTO", unit: "BIN", hide: true, category: "bool"},
    { name: "IPS High Pressure", unit: "BIN", hide: true, category: "bool"},
    { name: "IPS Low Pressure", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "CO Detected", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "TAS Traffic Advisory Active", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "TAWS or Terrain Alert", unit: "BIN", hide: true, category: "bool"},
    { name: "AIR(1)-GND(0) Status", unit: "BIN", hide: true, category: "bool"},
    { name: "Oxygen Status ON", unit: "BIN", hide: true, category: "bool"},
    { name: "Stall Warning ACTIVE", unit: "BIN", hide: true, category: "bool"},
    { name: "Pitot Heat ON", unit: "BIN", hide: true, category: "bool"},
    { name: "Pitot Heat - No Current", unit: "BIN", hide: true, category: "bool"},
    { name: "Parking Brake Set", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Selected Sensor - AHRS1", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected Sensor - AHRS2", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected Sensor - AHRS STBY", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected Sensor - ADC1", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected Sensor - ADC2", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected Sensor - ADC STBY", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected NAV Source - GPS", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected NAV Source - NAV1 (VOR)", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected NAV Source - NAV2 (VOR)", unit: "BIN", hide: true, category: "bool"}, //
    { name: "Selected NAV Source - NAV1 (LOC)", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected NAV Source - NAV2 (LOC)", unit: "BIN", hide: true, category: "bool"},
    { name: "Selected NAV Source - Invalid", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Gross Weight", unit: "Lbs", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Altitude (GIA1)", unit: "ft", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Altitude (GIA2)", unit: "ft", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "CDI Deviation (% full scale)", unit: "%", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Selected Course", unit: "Deg", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Battery 1 Current", unit: "A", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Selected Vertical Speed", unit: "FPM", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Heading/Yaw Rate (AHRS1)", unit: "deg/s", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Heading/Yaw Rate (AHRS2)", unit: "deg/s", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Hypoxia Timer", unit: "Minutes", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GARMIN HOBBS Time", unit: "Hours", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GARMIN FLIGHT Time", unit: "Hours", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GARMIN Engine Tach Time", unit: "Hours", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "AOA Temp Monitor", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Desired Track (DTK)", unit: "Deg", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Brake Temperature (Left)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Brake Temperature (Right)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS X-Track Distance (XTK)", unit: "N.M.", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Vertical Deviation (ft)", unit: "ft, GPS Only", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "VDI Deviation (% full scale)", unit: "%", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Main Bus 1 Voltage", unit: "V", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Main Bus 2 Voltage", unit: "V", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Essential Bus Voltage", unit: "V", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Alternator 1 Current", unit: "A", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Alternator 2 Current", unit: "A", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Percent Power", unit: "%", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Engine RPM", unit: "RPM", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Fuel Flow (GPH)", unit: "GPH", hide: true, category: "fuel"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Oxygen Pressure", unit: "PSIG", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Density Altitude (ADC1)", unit: "ft", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Density Altitude (ADC2)", unit: "ft", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Vup (GIA1)", unit: "kt", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Vup (GIA2)", unit: "kt", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Vnorth (GIA1)", unit: "kt", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Vnorth (GIA2)", unit: "kt", hide: true, category: "gia"}, //
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Status (GIA1)", unit: "ASCII", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Status (GIA2)", unit: "ASCII", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Veast (GIA1)", unit: "kt", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Veast (GIA2)", unit: "kt", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GAGL", unit: "ft", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Pressure Altitude (ADC1)", unit: "ft", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Pressure Altitude (ADC2)", unit: "ft", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "MACH (ADC1)", unit: "Mach", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "MACH (ADC2)", unit: "Mach", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Indicated Airspeed (ADC1)", unit: "kt", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Indicated Airspeed (ADC2)", unit: "kt", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ICD VER Char 7 & 8", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ICD VER Char 5 & 6", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ICD VER Char 3 & 4", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ICD VER Char 1 & 2", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "True Airspeed (ADC1)", unit: "kt", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "True Airspeed (ADC2)", unit: "kt", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "TAT (ADC1)", unit: "°C", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "TAT (ADC2)", unit: "°C", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Vertical Speed (ADC1)", unit: "fpm", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Vertical Speed (ADC2)", unit: "fpm", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Impact Pressure (ADC1)", unit: "mB", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Impact Pressure (ADC2)", unit: "mB", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Static Pressure (ADC1)", unit: "in-Hg", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Static Pressure (ADC2)", unit: "in-Hg", hide: true, category: "adc"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ANTI ICE CTL", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE QTY - UNKNOWN", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE QTY - LOW", unit: "BIN", hide: true, category: "bool"},
    { name: "AOA OVERHEAT", unit: "BIN", hide: true, category: "bool"},
    { name: "AUTO DESCENT - 60 SEC TO 14K", unit: "BIN", hide: true, category: "bool"},
    { name: "AUTO DESCENT - TO 14K", unit: "BIN", hide: true, category: "bool"},
    { name: "AUTO DESCENT - TO 12.5K", unit: "BIN", hide: true, category: "bool"},
    { name: "AUTO DESCENT - COMPLETE", unit: "BIN", hide: true, category: "bool"},
    { name: "BRAKE TEMP", unit: "BIN", hide: true, category: "bool"},
    { name: "CHT", unit: "BIN", hide: true, category: "bool"},
    { name: "CO LVL", unit: "BIN", hide: true, category: "bool"},
    { name: "ESS BUS - IN AIR", unit: "BIN", hide: true, category: "bool"},
    { name: "FUEL FLOW", unit: "BIN", hide: true, category: "bool"},
    { name: "FUEL IMBALANCE", unit: "BIN", hide: true, category: "bool"},
    { name: "FUEL LOW TOTAL", unit: "BIN", hide: true, category: "bool"},
    { name: "M BUS 1", unit: "BIN", hide: true, category: "bool"},
    { name: "M BUS 2", unit: "BIN", hide: true, category: "bool"},
    { name: "MAN PRESSURE >38\"", unit: "BIN", hide: true, category: "bool"},
    { name: "ESS BUS - ON GND", unit: "BIN", hide: true, category: "bool"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "OIL PRESSURE - GND", unit: "BIN", hide: true, category: "bool"},
    { name: "OIL TEMP", unit: "BIN", hide: true, category: "bool"},
    { name: "OXYGEN FAULT", unit: "BIN", hide: true, category: "bool"},
    { name: "OXYGEN QTY", unit: "BIN", hide: true, category: "bool"},
    { name: "RPM", unit: "BIN", hide: true, category: "bool"},
    { name: "SPIN SPIN SPIN", unit: "BIN", hide: true, category: "bool"},
    { name: "STALL - TONE", unit: "BIN", hide: true, category: "bool"}, //
    { name: "START ENGAGED", unit: "BIN", hide: true, category: "bool"},
    { name: "TIT", unit: "BIN", hide: true, category: "bool"},
    { name: "UNDERSPEED PROTECTION ACTIVE", unit: "BIN", hide: true, category: "bool"},
    { name: "FLAPS ICE", unit: "BIN", hide: true, category: "bool"},
    { name: "MAN PRESSURE >37.5\"", unit: "BIN", hide: true, category: "bool"},
    { name: "OIL PRESSURE - AIR", unit: "BIN", hide: true, category: "bool"},
    { name: "STALL - VOICE", unit: "BIN", hide: true, category: "bool"},
    { name: "STALL WARN FAIL", unit: "BIN", hide: true, category: "bool"},
    { name: "OXYGEN RQD (>12.5K/40 MIN)", unit: "BIN", hide: true, category: "bool"},
    { name: "OXYGEN RQD (>14K/5MIN)", unit: "BIN", hide: true, category: "bool"},
    { name: "FUEL LOW LEFT", unit: "BIN", hide: true, category: "bool"},
    { name: "FUEL LOW RIGHT", unit: "BIN", hide: true, category: "bool"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ALT 1 (ON-GND)", unit: "BIN", hide: true, category: "bool"},
    { name: "ALT 2 (ON-GND)", unit: "BIN", hide: true, category: "bool"}, //
    { name: "ALT AIR  OPEN", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE HEAT", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE LEVEL (LT)", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE PRESS - LOW (NORMAL)", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE PRESS - HI", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE QTY - IMBALANCE", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE QTY - LOW", unit: "BIN", hide: true, category: "duplicate"},
    { name: "ANTI ICE SPEED - LOW", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE SPEED - HI", unit: "BIN", hide: true, category: "bool"},
    { name: "AP MISCOMPARE", unit: "BIN", hide: true, category: "bool"},
    { name: "AP/PFD DIF ADC", unit: "BIN", hide: true, category: "bool"},
    { name: "AP/PFD DIF AHRS", unit: "BIN", hide: true, category: "bool"},
    { name: "AVIONICS OFF", unit: "BIN", hide: true, category: "bool"},
    { name: "BATT 1 (IN-AIR)", unit: "BIN", hide: true, category: "bool"},
    { name: "BRAKE TEMP", unit: "BIN", hide: true, category: "duplicate"},
    { name: "CHT", unit: "BIN", hide: true, category: "duplicate"},
    { name: "ANTI ICE PRESS - LOW (MAX, HIGH)", unit: "BIN", hide: true, category: "bool"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "FLAP OVERSPEED", unit: "BIN", hide: true, category: "bool"},
    { name: "TAKEOFF FLAPS", unit: "BIN", hide: true, category: "bool"},
    { name: "FUEL IMBALANCE", unit: "BIN", hide: true, category: "bool"},
    { name: "FUEL LOW TOTAL", unit: "BIN", hide: true, category: "bool"},
    { name: "HYPOXIA ALERT", unit: "BIN", hide: true, category: "bool"},
    { name: "M BUS 1 (ON-GND)", unit: "BIN", hide: true, category: "bool"},
    { name: "M BUS 2 (ON-GND)", unit: "BIN", hide: true, category: "bool"},
    { name: "MAN PRESSURE > 37\"", unit: "BIN", hide: true, category: "bool"},
    { name: "NO ADC MODES", unit: "BIN", hide: true, category: "bool"},
    { name: "NO VERT MODES", unit: "BIN", hide: true, category: "bool"},
    { name: "OIL PRESSURE (IN-AIR)", unit: "BIN", hide: true, category: "bool"},
    { name: "OIL TEMP", unit: "BIN", hide: true, category: "bool"},
    { name: "OXYGEN QTY", unit: "BIN", hide: true, category: "bool"},
    { name: "OXYGEN RQD (>12.5K/30MIN)", unit: "BIN", hide: true, category: "bool"},
    { name: "PARK BRAKE (RPM>2K)", unit: "BIN", hide: true, category: "bool"},
    { name: "PITOT HEAT FAIL", unit: "BIN", hide: true, category: "bool"},
    { name: "PITOT HEAT REQD (IN-AIR)", unit: "BIN", hide: true, category: "bool"},
    { name: "START ENGAGED", unit: "BIN", hide: true, category: "bool"},
    { name: "M BUS 1 (IN-AIR)", unit: "BIN", hide: true, category: "bool"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "M BUS 2 (IN-AIR)", unit: "BIN", hide: true, category: "bool"},
    { name: "MAN PRESSURE > 36.5\"", unit: "BIN", hide: true, category: "bool"},
    { name: "OIL PRESSURE (ON-GND)", unit: "BIN", hide: true, category: "bool"},
    { name: "PARK BRAKE (RPM< 2K)", unit: "BIN", hide: true, category: "bool"},
    { name: "PITOT HEAT REQD (ON-GND)", unit: "BIN", hide: true, category: "bool"},
    { name: "ALT 1 (IN-AIR)", unit: "BIN", hide: true, category: "bool"},
    { name: "ALT 2 (IN-AIR)", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE LEVEL (RT)", unit: "BIN", hide: true, category: "bool"},
    { name: "BATT 1 (ON-GND)", unit: "BIN", hide: true, category: "bool"},
    { name: "ANTI ICE TEMP", unit: "BIN", hide: true, category: "bool"},
    { name: "AOA/STALL WARN", unit: "BIN", hide: true, category: "bool"},
    { name: "OXYGEN RQD (>14K/5MIN)", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Normalized AOA", unit: "-", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Fuel Remaining", unit: "Gal", hide: true, category: "fuel"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "FLT ID Char 1-4", unit: "Digit", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "FLT ID Char 5-8", unit: "Digit", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Fuel Used (Totalizer)", unit: "Gal, calculated", hide: true, category: "fuel"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Initial Usable Fuel", unit: "Gal", hide: true, category: "fuel"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Anti Ice Tank Quantity (Left)", unit: "Gal", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Anti Ice Tank Quantity (Right)", unit: "Gal", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Fuel Quantity (Left)", unit: "Gal, sensed", hide: true, category: "fuel"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Fuel Quantity (Right)", unit: "Gal, sensed", hide: true, category: "fuel"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Tail Num Char 1 & 2", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Tail Num Char 3 & 4", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Tail Num Char 5 & 6", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Tail Num Char 7 & 8", unit: "ASCII", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Coupled Lateral Mode Code - GIA1", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Coupled Lateral Mode Code - GIA2", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Coupled Vertical  Mode Code - GIA1", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Coupled Vertical  Mode Code - GIA2", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Armed Lateral Mode Code - GIA1", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Armed Lateral Mode Code - GIA2", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Armed Primary Vertical  Mode Code - GIA1", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Armed Primary Vertical  Mode Code - GIA2", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Armed Secondary Vertical  Mode Code - GIA1", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Armed Secondary Vertical  Mode Code - GIA2", unit: "Code", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Low Thrust Throttle ESP Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "High Thrust Throttle ESP Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "Throttle ESP Low Enabled", unit: "BIN", hide: true, category: "bool"},
    { name: "Throttle ESP High Enabled", unit: "BIN", hide: true, category: "bool"},
    { name: "Throttle ESP Failed", unit: "BIN", hide: true, category: "bool"},
    { name: "Hi Mach ESP Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "ESP Enabled by Pilot", unit: "BIN", hide: true, category: "bool"},
    { name: "AOA Stall ESP mode failed", unit: "BIN", hide: true, category: "bool"},
    { name: "High IAS ESP Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "Stall Warning ESP Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "AOA ESP Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "High Pitch ESP Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "Low Pitch ESP Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "Roll ESP Engaged in Positive direction", unit: "BIN", hide: true, category: "bool"},
    { name: "Roll ESP Engaged in Negative direction", unit: "BIN", hide: true, category: "bool"},
    { name: "ESP Pitch mode Absolute", unit: "BIN", hide: true, category: "bool"},
    { name: "ESP Enabled", unit: "BIN", hide: true, category: "bool"},
    { name: "ESP Failed", unit: "BIN", hide: true, category: "bool"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Low Thrust Throttle ESP Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "High Thrust Throttle ESP Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Throttle ESP Low Enabled", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Throttle ESP High Enabled", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Throttle ESP Failed", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Hi Mach ESP Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "ESP Enabled by Pilot", unit: "BIN", hide: true, category: "duplicate"},
    { name: "AOA Stall ESP mode failed", unit: "BIN", hide: true, category: "duplicate"},
    { name: "High IAS ESP Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Stall Warning ESP Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "AOA ESP Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "High Pitch ESP Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Low Pitch ESP Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Roll ESP Engaged in Positive direction", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Roll ESP Engaged in Negative direction", unit: "BIN", hide: true, category: "duplicate"},
    { name: "ESP Pitch mode Absolute", unit: "BIN", hide: true, category: "duplicate"},
    { name: "ESP Enabled", unit: "BIN", hide: true, category: "duplicate"},
    { name: "ESP Failed", unit: "BIN", hide: true, category: "duplicate"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "AFCS - AP/FD Engaged", unit: "BIN", hide: true, category: "bool"},
    { name: "Yaw Damper On", unit: "BIN", hide: true, category: "bool"},
    { name: "On-side FD Active", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved for Pilot/Copilot Pitch Trim Up", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved for Pilot/Copilot Pitch Trim Down", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "AFCS - AP/FD Engaged", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Yaw Damper On", unit: "BIN", hide: true, category: "duplicate"},
    { name: "On-side FD Active", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Reserved for Pilot/Copilot Pitch Trim Up", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Reserved for Pilot/Copilot Pitch Trim Down", unit: "BIN", hide: true, category: "duplicate"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ALTITUDE SEL - CLB", unit: "BIN", hide: true, category: "bool"},
    { name: "ALTITUDE SEL - DESC", unit: "BIN", hide: true, category: "bool"},
    { name: "AOA FAIL", unit: "BIN", hide: true, category: "bool"},
    { name: "ARE YOU ALERT", unit: "BIN", hide: true, category: "bool"},
    { name: "COURSE SEL", unit: "BIN", hide: true, category: "bool"},
    { name: "FUEL IMBALANCE", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "OXYGEN LEFT ON", unit: "BIN", hide: true, category: "bool"},
    { name: "OXYGEN QTY", unit: "BIN", hide: true, category: "bool"},
    { name: "PUMP BACKUP", unit: "BIN", hide: true, category: "bool"},
    { name: "HDG MODE", unit: "BIN", hide: true, category: "bool"},
    { name: "ROL MODE", unit: "BIN", hide: true, category: "bool"},
    { name: "FLAPS CLIMB", unit: "BIN", hide: true, category: "bool"},
    { name: "VNAV NOT ARMED", unit: "BIN", hide: true, category: "bool"},
    { name: "VNAV ALT SEL", unit: "BIN", hide: true, category: "bool"},
    { name: "CHECK OXYGEN (ON/30 min)", unit: "BIN", hide: true, category: "bool"},
    { name: "CHECK OXYGEN (>10K/3 sec)", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ALT MISCOMP", unit: "BIN", hide: true, category: "bool"},
    { name: "IAS MISCOMP", unit: "BIN", hide: true, category: "bool"},
    { name: "HDG MISCOMP", unit: "BIN", hide: true, category: "bool"},
    { name: "PIT MISCOMP", unit: "BIN", hide: true, category: "bool"},
    { name: "ROL MISCOMP", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "ALT NO COMP", unit: "BIN", hide: true, category: "bool"},
    { name: "IAS NO COMP", unit: "BIN", hide: true, category: "bool"},
    { name: "HDG NO COMP", unit: "BIN", hide: true, category: "bool"},
    { name: "PIT NO COMP", unit: "BIN", hide: true, category: "bool"},
    { name: "ROL NO COMP", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "ANTI ICE QTY", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved for CO DET FAIL", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved for CO DET SRVC", unit: "BIN", hide: true, category: "bool"},
    { name: "ESP CONFIG", unit: "BIN", hide: true, category: "bool"},
    { name: "EXIT ICING - 30 MIN", unit: "BIN", hide: true, category: "bool"},
    { name: "FAILED PATH", unit: "BIN", hide: true, category: "bool"},
    { name: "MFD FAN FAIL", unit: "BIN", hide: true, category: "bool"},
    { name: "PFD FAN FAIL", unit: "BIN", hide: true, category: "bool"},
    { name: "EXIT ICING - 60 MIN", unit: "BIN", hide: true, category: "bool"},
    { name: "EXIT ICING - 90 MIN", unit: "BIN", hide: true, category: "bool"},
    { name: "EXIT ICING - 120 MIN", unit: "BIN", hide: true, category: "bool"},
    { name: "ESP DEGRADE", unit: "BIN", hide: true, category: "bool"},
    { name: "ESP FAIL", unit: "BIN", hide: true, category: "bool"},
    { name: "ESP OFF", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Latitude (GIA1)", unit: "Deg", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Latitude (GIA2)", unit: "Deg", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Longitude (GIA1)", unit: "Deg", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "GPS Longitude (GIA2)", unit: "Deg", hide: true, category: "gia"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Ground Speed", unit: "kt", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Wind Speed", unit: "kt", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Wind Direction", unit: "Deg", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Heading (AHRS1)", unit: "Deg", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Heading (AHRS2)", unit: "Deg", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "EGT (cyl 1)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "EGT (cyl 3)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "EGT (cyl 5)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "EGT (cyl 2)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "EGT (cyl 4)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "EGT (cyl 6)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Pitch Angle (AHRS1)", unit: "Deg", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Pitch Angle (AHRS2)", unit: "Deg", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Roll Angle (AHRS1)", unit: "Deg", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Roll Angle (AHRS2)", unit: "Deg", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Pitch Rate  (AHRS1)", unit: "deg/s", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Pitch Rate  (AHRS2)", unit: "deg/s", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Roll Rate  (AHRS1)", unit: "deg/s", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Roll Rate  (AHRS2)", unit: "deg/s", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Longitudinal Acceleration (AHRS1)", unit: "g", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Longitudinal Acceleration (AHRS2)", unit: "g", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Lateral Acceleration (AHRS1)", unit: "g", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Lateral Acceleration (AHRS2)", unit: "g", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Normal Acceleration (AHRS1)", unit: "g", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Normal Acceleration (AHRS2)", unit: "g", hide: true, category: "ahrs"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Oil Temperature", unit: "°C", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "CHT (cyl 1)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "CHT (cyl 3)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "CHT (cyl 5)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Oil Pressure", unit: "PSI", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "CHT (cyl 2)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "CHT (cyl 4)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "CHT (cyl 6)", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Manifold Pressure", unit: "in. Hg", hide: true, category: "general"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Manifold Air Temperature", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Left TIT", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Right TIT", unit: "°F", hide: true, category: "generaltemps"},
    { name: "SSM", unit: "", hide: true, category: ""},
    { name: "Rudder Mistrim Right", unit: "BIN", hide: true, category: "bool"},
    { name: "Rudder Mistrim Left", unit: "BIN", hide: true, category: "bool"},
    { name: "Aileron Mistrim Right", unit: "BIN", hide: true, category: "bool"},
    { name: "Aileron Mistrim Left", unit: "BIN", hide: true, category: "bool"},
    { name: "Elevator Mistrim Down", unit: "BIN", hide: true, category: "bool"},
    { name: "Elevator Mistrim Up", unit: "BIN", hide: true, category: "bool"},
    { name: "Pitch Trim Failure", unit: "BIN", hide: true, category: "bool"},
    { name: "Yaw Damper Failure", unit: "BIN", hide: true, category: "bool"},
    { name: "Roll Failure", unit: "BIN", hide: true, category: "bool"},
    { name: "Pitch Failure", unit: "BIN", hide: true, category: "bool"},
    { name: "System Failure", unit: "BIN", hide: true, category: "bool"},
    { name: "PFT - In progress", unit: "BIN", hide: true, category: "bool"},
    { name: "PFT - Failed", unit: "BIN", hide: true, category: "bool"},
    { name: "EDM", unit: "BIN", hide: true, category: "bool"},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
    { name: "Reserved", unit: "", hide: true, category: ""},
   
];

//Only columns pertaining to engine/fuel
export const engineHeaders = [
    "LocalDate", "LocalTime", "UTCOffset",
    "FQtyL", "FQtyR",
    "E1FFlow", "E1OilT", "E1OilP",
    "E1MAP", "E1RPM", "E1PercentPwr",
    "E1CHT1", "E1CHT2", "E1CHT3",
    "E1CHT4", "E1CHT5", "E1CHT6",
    "E1EGT1", "E1EGT2", "E1EGT3",
    "E1EGT4", "E1EGT5", "E1EGT6",
    "E1TIT1", "E1TIT2"
]

//Remove "E1" and fuel qty headers
export const avionicsHeaders = [
    "LocalDate", "LocalTime", "UTCOffset",
    "AtvWpt", "Lat", "Long",
    "AltB", "BaroA", "AltMSL",
    "OAT", "IAS", "GndSpd",
    "VSpd", "Pitch", "Roll",
    "LatAc", "NormAc", "HDG",
    "TRK", "volt1", "volt2",
    "amp1", "AltGPS",
    "TAS", "HSIS", "CRS",
    "NAV1", "NAV2", "COM1",
    "COM2", "HCDI", "VCDI",
    "WndSpd", "WndDr", "WptDst",
    "WptBrg", "MagVar", "AfcsOn",
    "RollM", "PitchM", "RollC",
    "PitchC", "VSpdG", "GPSfix",
    "HAL", "VAL", "HPLwas",
    "HPLfd", "VPLwas"
]

//Only EGT headers to check for high values
export const egtHeaders = [
    "E1EGT1", "E1EGT2", "E1EGT3",
    "E1EGT4", "E1EGT5", "E1EGT6",
]

//Only CHT headers to check for high values
export const chtHeaders = [
    "E1CHT1", "E1CHT2", "E1CHT3",
    "E1CHT4", "E1CHT5", "E1CHT6",
]
